[project]
name = "nonlocalgames"
version = "1.0.0"
authors = [
  { name="Jim Furches", email="jim.furches@gmail.com" },
]
description = "Algorithms for solving non-local games"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "adapt-gym",
    "numpy>=2.3.0",
    "openfermion>=1.7.1",
    "qiskit>=2.0.2",
    "qiskit-aer>=0.17.1",
    "qiskit-ibm-provider>=0.11.0",
    "qiskit-ibm-runtime>=0.40.1",
    "scipy>=1.15.3",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv.sources]
adapt-gym = { path = "../adapt-gym", editable = true }

[dependency-groups]
dev = [
    "pytest>=8.4.0",
]
